export const PENDING_STATUS = 'PENDING';
export const SUCCESS_STATUS = 'SUCCESS';
export const ERROR_STATUS = 'ERROR';

export const DO_LOGIN = 'DO_LOGIN';
export const DO_REGISTER = 'DO_REGISTER';
export const DO_FORGOT_PASSWORD = 'DO_FORGOT_PASSWORD';

export const FETCH_FACILITY_EVENT = 'FETCH_FACILITY_EVENT';
